package org.eder.learning.ws.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "TempVerterImplService", 
				targetNamespace = "http://soap.ws.learning.eder.org/", 
				wsdlLocation = "http://localhost:9901/TempVerter?wsdl")
public class TempVerterImplService extends Service {
	private final static URL TEMPVERTERIMPLSERVICE_WSDL_LOCATION;
	private final static WebServiceException TEMPVERTERIMPLSERVICE_EXCEPTION;
	private final static QName TEMPVERTERIMPLSERVICE_QNAME = new QName("http://soap.ws.learning.eder.org/", "TempVerterImplService");
	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL("http://localhost:9901/TempVerter?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		TEMPVERTERIMPLSERVICE_WSDL_LOCATION = url;
		TEMPVERTERIMPLSERVICE_EXCEPTION = e;
	}

	public TempVerterImplService() {
		super(__getWsdlLocation(), TEMPVERTERIMPLSERVICE_QNAME);
	}

	public TempVerterImplService(WebServiceFeature... features) {
		super(__getWsdlLocation(), TEMPVERTERIMPLSERVICE_QNAME, features);
	}

	public TempVerterImplService(URL wsdlLocation) {
		super(wsdlLocation, TEMPVERTERIMPLSERVICE_QNAME);
	}

	public TempVerterImplService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, TEMPVERTERIMPLSERVICE_QNAME, features);
	}

	public TempVerterImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public TempVerterImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns TempVerter
	 */
	@WebEndpoint(name = "TempVerterImplPort")
	public TempVerter getTempVerterImplPort() {
		return super.getPort(new QName("http://soap.ws.learning.eder.org/", "TempVerterImplPort"), TempVerter.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns TempVerter
	 */
	@WebEndpoint(name = "TempVerterImplPort")
	public TempVerter getTempVerterImplPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://soap.ws.learning.eder.org/", "TempVerterImplPort"), TempVerter.class, features);
	}

	private static URL __getWsdlLocation() {
		if (TEMPVERTERIMPLSERVICE_EXCEPTION != null) {
			throw TEMPVERTERIMPLSERVICE_EXCEPTION;
		}
		return TEMPVERTERIMPLSERVICE_WSDL_LOCATION;
	}
}
